name: Build, Test (Turbo) and Upload Coverage to SeaLights

on:
  workflow_dispatch:
  schedule:
  # run at 3:18 UTC every day
    - cron: "* 3 * * *"
  push:
    branches: [ test-pr ]
  pull_request:
    branches: [ saelights-steps ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary for SeaLights to correctly analyze git history for changed files

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Specify your Node.js version
          cache: 'yarn' # Or 'npm' or 'pnpm' depending on your lockfile

      - name: Install dependencies (including Turborepo globally or locally)
        run: |
          yarn install --immutable # Or your package manager's install command
          # If turbo is not part of your devDependencies and needs to be global:
          npm install -g turbo
          # Or ensure it's available via npx if listed in devDependencies

      - name: Install jest-junit
        run: yarn add --dev jest-junit

      - name: Install istanbul-merge
        run: yarn add --dev istanbul-merge

      - name: Install SeaLights Agent
        run: |
          npm show slnodejs dist-tags
          npm install slnodejs@latest

      - name: SeaLights config
        env:
          SEALIGHTS_AGENT_TOKEN: ${{ secrets.SEALIGHTS_AGENT_TOKEN }}
          SL_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          SL_APP_NAME: "rhdh"
        run: |
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            BUILD_SESSION_ID="pr-${{ github.event.pull_request.number }}-${{ github.sha }}"
          else
            BUILD_SESSION_ID="build-${{ github.sha }}"
          fi
          echo "BUILD_SESSION_ID=${BUILD_SESSION_ID}" >> $GITHUB_ENV

          npx slnodejs config --token $SEALIGHTS_AGENT_TOKEN \
                              --buildsessionid $BUILD_SESSION_ID \
                              --appname $SL_APP_NAME \
                              --branch $SL_BRANCH_NAME \
                              --build $BUILD_SESSION_ID
                              --scm git
                              --workspacepath .

      - name: SeaLights initial scan
        run: npx slnodejs scan --buildsessionid $BUILD_SESSION_ID --scm git --workspacepath "." --token ${{ secrets.SEALIGHTS_AGENT_TOKEN }} --babylonPlugins "jsx,typescript"

      - name: SeaLights tests start
        run: npx slnodejs start --teststage unittests --buildsessionid $BUILD_SESSION_ID --token ${{ secrets.SEALIGHTS_AGENT_TOKEN }}

      - name: Run tests
        #if: ${{ steps.check-image.outputs.is_skipped != 'true' }}
        run: yarn run test --continue --affected

      - name: Install dynamic plugin dependencies
        #if: ${{ steps.check-image.outputs.is_skipped != 'true' }}
        run: cd ./dynamic-plugins && yarn install && cd ..

      - name: Verify dynamic plugin wrappers
        #if: ${{ steps.check-image.outputs.is_skipped != 'true' }}
        run: cd ./dynamic-plugins && yarn test && cd ..

      - name: Merge tests coverage reports
        run: npx  istanbul-merge --out coverage.json packages/backend/coverage/coverage-final.json packages/app/coverage/coverage-final.json

      - name: SeaLights upload coverage
        run: npx slnodejs nycReport --teststage unittests --buildsessionid $BUILD_SESSION_ID --report coverage.json --token ${{ secrets.SEALIGHTS_AGENT_TOKEN }}
      - name: SeaLights upload results
        run: npx slnodejs uploadReports --teststage unittests --buildsessionid $BUILD_SESSION_ID --reportfile packages/backend/junit.xml --reportfile packages/app/junit.xml --token ${{ secrets.SEALIGHTS_AGENT_TOKEN }}

      - name: SeaLights tests end
        run: npx slnodejs end --buildsessionid $BUILD_SESSION_ID --token ${{ secrets.SEALIGHTS_AGENT_TOKEN }}