name: Build, Test (Turbo) and Upload Coverage to SeaLights

on:
  workflow_dispatch:
  schedule:
  # run at 3:18 UTC every day
    - cron: "* 3 * * *"
  push:
    branches: [ test-pr ]
  pull_request:
    branches: [ saelights-steps ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary for SeaLights to correctly analyze git history for changed files

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Specify your Node.js version
          cache: 'yarn' # Or 'npm' or 'pnpm' depending on your lockfile

      - name: Install dependencies (including Turborepo globally or locally)
        run: |
          yarn install --immutable # Or your package manager's install command
          # If turbo is not part of your devDependencies and needs to be global:
          npm install -g turbo
          # Or ensure it's available via npx if listed in devDependencies

      - name: Install jest-junit
        run: yarn add --dev jest-junit

      - name: Install istanbul-merge
        run: yarn add --dev istanbul-merge

      - name: Install SeaLights Agent
        run: |
          npm show slnodejs dist-tags
          npm i slnodejs

      - name: Write SeaLights token into file
        run: echo "${SEALIGHTS_AGENT_TOKEN}" > sltoken.txt
        env:
          SEALIGHTS_AGENT_TOKEN: '${{secrets.SEALIGHTS_AGENT_TOKEN}}'

      - name: SeaLights config
        env:
          SEALIGHTS_AGENT_TOKEN: ${{ secrets.SEALIGHTS_AGENT_TOKEN }}
          SL_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          SL_APP_NAME: "rhdh"
          NODE_DEBUG: sl
          LATEST_COMMIT_SHA: ${{ github.sha }}
        run: |
          echo "BUILD_TIME=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
          npx slnodejs config --tokenfile ./sltoken.txt --appname $SL_APP_NAME --branch $SL_BRANCH_NAME --build "$BUILD_TIME:$LATEST_COMMIT_SHA"
          ls -ltra .

      - name: SeaLights initial scan
        env:
          NODE_DEBUG: sl
        run: npx slnodejs scan --buildsessionidfile buildSessionId --scm git --workspacepath "." --tokenfile ./sltoken.txt --babylonPlugins "jsx,typescript"

      - name: SeaLights tests start
        run: npx slnodejs start --teststage unittests --buildsessionidfile buildSessionId --tokenfile ./sltoken.txt

      - name: Run tests
        #if: ${{ steps.check-image.outputs.is_skipped != 'true' }}
        run: |
          yarn install --immutable
          yarn run test --continue --affected

      - name: Install dynamic plugin dependencies
        #if: ${{ steps.check-image.outputs.is_skipped != 'true' }}
        run: cd ./dynamic-plugins && yarn install && cd ..

      - name: Verify dynamic plugin wrappers
        #if: ${{ steps.check-image.outputs.is_skipped != 'true' }}
        run: cd ./dynamic-plugins && yarn test && cd ..

      - name: Merge tests coverage reports
        run: npx  istanbul-merge --out coverage.json packages/backend/coverage/coverage-final.json packages/app/coverage/coverage-final.json

      - name: SeaLights upload coverage
        run: npx slnodejs nycReport --teststage unittests --buildsessionidfile buildSessionId --report coverage.json --tokenfile ./sltoken.txt
      - name: SeaLights upload results
        run: npx slnodejs uploadReports --teststage unittests --buildsessionidfile buildSessionId --reportfile packages/backend/junit.xml --reportfile packages/app/junit.xml --tokenfile ./sltoken.txt

      - name: SeaLights tests end
        run: npx slnodejs end --buildsessionidfile buildSessionId --tokenfile ./sltoken.txt