name: Playwright Tests
on:
  push:
    branches: [ test-pr ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Playwright Browsers
      run: |
        yarn install --immutable
        yarn run build --continue --affected

    - name: Run Playwright tests
      run: |
          cd ./e2e-tests
          yarn playwright install chromium
          yarn install --immutable
          npx playwright test --project=any-test && cd ..

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
